export const generateMetadata = ({
  title = `${process.env.NEXT_PUBLIC_APP_NAME} - Explore, Develop, Grow, Excel`,
  description = `${process.env.NEXT_PUBLIC_APP_NAME} is VIT Pune's Annual Student Summit. A transformative platform offering students a unique opportunity to gain practical insights from industry mentors.`,
  image = "/assets/thumbnail.png",
  iconUrl = "/assets/abhivriddhi logo.png",
  keywords = [
    "Abhivriddhi",
    "Abhivriddhi VIT Pune",
    "edge",
    "edge 26",
    "EDGE",
    "EDGE 2026",
    "EDGE 26",
    "abhivriddhi edge",
    "abhivriddhi vit",
    "abhivriddhi vit pune",
    "edge.abhivriddhivitpune.in",
    "abhivriddhivitpune",
    "VIT Pune",
    "Student Summit",
    "Explore",
    "Develop",
    "Grow",
    "Excel",
    "Industry Mentors",
  ],
  canonical = `${process.env.NEXT_PUBLIC_SITE_URL}`,
  noIndex = false,
} = {}) => ({
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL),
  title,
  description,
  keywords: keywords.join(", "),
  icons: [
    {
      rel: "icon",
      url: iconUrl,
      type: "image/png",
      sizes: "2048x564",
    },
    {
      rel: "apple-touch-icon",
      url: iconUrl,
      sizes: "2048x564",
    },
  ],
  openGraph: {
    type: "website",
    title,
    description,
    url: canonical,
    ...(image && {
      images: [
        {
          url: image,
          width: 1200,
          height: 630,
        },
      ],
    }),
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
    creator: "@sohamkolhatkar",
    ...(image && { images: [image] }),
  },
  ...(noIndex && { robots: { index: false, follow: false } }),
  link: [
    {
      rel: "canonical",
      href: canonical,
    },
  ],
});
